### ISSUE TITLE
Unable to process command to add problem matcher

### ISSUE THREAD

**Issue by xMikux** [ComunidadAylas/PackSquash-action#3]
When i using this action, to package the resourcepacks, it will fail, but artifacts still will upload, and Optimized zip no error too.
![image](https://user-images.githubusercontent.com/26039249/130222489-3afa738f-5bc1-4263-acb1-14f17ccd2f09.png)

**Comment by AlexTMjugador** [comment]
Thanks for trying out the action and reporting this issue!

By the looks of it, I'd say that it is a somewhat benign problem, as it is just related to the problem matcher used for highlighting PackSquash errors and warnings not being found. But this benign problem may prevent the action from working properly if the previously generated ZIP file turns out to be invalid, so it is important to fix.

I'll investigate a solution to this problem, hopefully without reverting the entire problem matching feature.

**Comment by AlexTMjugador** [comment]
In the latest commits I've fixed the problem reported by this issue, and also another ones relating to GitHub API authentication tokens not being used properly by the shell script.

Please let me know if everything works fine for you now, and if so we can close this issue :+1:

**Comment by xMikux** [comment]
yeah! it work now, it have big green check mark, and now i can remove ``if: ${{ failure() }}`` on action.

**Comment by AlexTMjugador** [comment]
For the record, I'd like to add that [I've been developing a fix](https://github.com/ComunidadAylas/PackSquash-action/commit/cfe586b2427b0ed67a5dfa505d25539a9fc25b9a) to this error still happening sometimes, as it seems that the original fix that made its way to v2.0.0 was incomplete and relied on unspecified behavior of the runner. It should be better now, and this fix will be released in the next patch version.
